name: recipe_book_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.3
  cloud_firestore: ^5.6.6
  firebase_storage_web: ^3.10.12
  image_picker: ^1.0.7
  path: ^1.9.0
  http: ^0.13.6
  firebase_auth: ^5.5.2
  google_sign_in: ^6.2.1
  uuid: ^4.2.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
