// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGW1mMkHvgSW8738cHmRaouPY_yGSTFAg',
    appId: '1:624677150820:web:a49aaade51d84da6443f71',
    messagingSenderId: '624677150820',
    projectId: 'recipebookapp-78',
    authDomain: 'recipebookapp-78.firebaseapp.com',
    storageBucket: 'recipebookapp-78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzY6OLVkubIYc-H4h9_Y2rvhAJfYUcF84',
    appId: '1:624677150820:android:08bf4bf4f6eb2a43443f71',
    messagingSenderId: '624677150820',
    projectId: 'recipebookapp-78',
    storageBucket: 'recipebookapp-78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVmDVcRbhFsr1NTcOG4eMlcAwEaAmZ-1E',
    appId: '1:624677150820:ios:87e14e08df44c4e5443f71',
    messagingSenderId: '624677150820',
    projectId: 'recipebookapp-78',
    storageBucket: 'recipebookapp-78.firebasestorage.app',
    iosBundleId: 'com.example.recipeBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVmDVcRbhFsr1NTcOG4eMlcAwEaAmZ-1E',
    appId: '1:624677150820:ios:87e14e08df44c4e5443f71',
    messagingSenderId: '624677150820',
    projectId: 'recipebookapp-78',
    storageBucket: 'recipebookapp-78.firebasestorage.app',
    iosBundleId: 'com.example.recipeBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGW1mMkHvgSW8738cHmRaouPY_yGSTFAg',
    appId: '1:624677150820:web:fc26451a293d4fb0443f71',
    messagingSenderId: '624677150820',
    projectId: 'recipebookapp-78',
    authDomain: 'recipebookapp-78.firebaseapp.com',
    storageBucket: 'recipebookapp-78.firebasestorage.app',
  );
}
